/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IaBienUsadaRouteImport } from './routes/ia-bien-usada'
import { Route as Harness03RouteImport } from './routes/harness-03'
import { Route as Harness02RouteImport } from './routes/harness-02'
import { Route as Harness01RouteImport } from './routes/harness-01'
import { Route as IndexRouteImport } from './routes/index'

const IaBienUsadaRoute = IaBienUsadaRouteImport.update({
  id: '/ia-bien-usada',
  path: '/ia-bien-usada',
  getParentRoute: () => rootRouteImport,
} as any)
const Harness03Route = Harness03RouteImport.update({
  id: '/harness-03',
  path: '/harness-03',
  getParentRoute: () => rootRouteImport,
} as any)
const Harness02Route = Harness02RouteImport.update({
  id: '/harness-02',
  path: '/harness-02',
  getParentRoute: () => rootRouteImport,
} as any)
const Harness01Route = Harness01RouteImport.update({
  id: '/harness-01',
  path: '/harness-01',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harness-01': typeof Harness01Route
  '/harness-02': typeof Harness02Route
  '/harness-03': typeof Harness03Route
  '/ia-bien-usada': typeof IaBienUsadaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harness-01': typeof Harness01Route
  '/harness-02': typeof Harness02Route
  '/harness-03': typeof Harness03Route
  '/ia-bien-usada': typeof IaBienUsadaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/harness-01': typeof Harness01Route
  '/harness-02': typeof Harness02Route
  '/harness-03': typeof Harness03Route
  '/ia-bien-usada': typeof IaBienUsadaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/harness-01'
    | '/harness-02'
    | '/harness-03'
    | '/ia-bien-usada'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/harness-01' | '/harness-02' | '/harness-03' | '/ia-bien-usada'
  id:
    | '__root__'
    | '/'
    | '/harness-01'
    | '/harness-02'
    | '/harness-03'
    | '/ia-bien-usada'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Harness01Route: typeof Harness01Route
  Harness02Route: typeof Harness02Route
  Harness03Route: typeof Harness03Route
  IaBienUsadaRoute: typeof IaBienUsadaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ia-bien-usada': {
      id: '/ia-bien-usada'
      path: '/ia-bien-usada'
      fullPath: '/ia-bien-usada'
      preLoaderRoute: typeof IaBienUsadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-03': {
      id: '/harness-03'
      path: '/harness-03'
      fullPath: '/harness-03'
      preLoaderRoute: typeof Harness03RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-02': {
      id: '/harness-02'
      path: '/harness-02'
      fullPath: '/harness-02'
      preLoaderRoute: typeof Harness02RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-01': {
      id: '/harness-01'
      path: '/harness-01'
      fullPath: '/harness-01'
      preLoaderRoute: typeof Harness01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Harness01Route: Harness01Route,
  Harness02Route: Harness02Route,
  Harness03Route: Harness03Route,
  IaBienUsadaRoute: IaBienUsadaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
