/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VonNeumannRouteImport } from './routes/von-neumann'
import { Route as Mod09RouteImport } from './routes/mod-09'
import { Route as Mod08RouteImport } from './routes/mod-08'
import { Route as Mod06RouteImport } from './routes/mod-06'
import { Route as IaBienUsadaRouteImport } from './routes/ia-bien-usada'
import { Route as Harness05RouteImport } from './routes/harness-05'
import { Route as Harness04RouteImport } from './routes/harness-04'
import { Route as Harness03RouteImport } from './routes/harness-03'
import { Route as Harness02RouteImport } from './routes/harness-02'
import { Route as Harness01RouteImport } from './routes/harness-01'
import { Route as IndexRouteImport } from './routes/index'

const VonNeumannRoute = VonNeumannRouteImport.update({
  id: '/von-neumann',
  path: '/von-neumann',
  getParentRoute: () => rootRouteImport,
} as any)
const Mod09Route = Mod09RouteImport.update({
  id: '/mod-09',
  path: '/mod-09',
  getParentRoute: () => rootRouteImport,
} as any)
const Mod08Route = Mod08RouteImport.update({
  id: '/mod-08',
  path: '/mod-08',
  getParentRoute: () => rootRouteImport,
} as any)
const Mod06Route = Mod06RouteImport.update({
  id: '/mod-06',
  path: '/mod-06',
  getParentRoute: () => rootRouteImport,
} as any)
const IaBienUsadaRoute = IaBienUsadaRouteImport.update({
  id: '/ia-bien-usada',
  path: '/ia-bien-usada',
  getParentRoute: () => rootRouteImport,
} as any)
const Harness05Route = Harness05RouteImport.update({
  id: '/harness-05',
  path: '/harness-05',
  getParentRoute: () => rootRouteImport,
} as any)
const Harness04Route = Harness04RouteImport.update({
  id: '/harness-04',
  path: '/harness-04',
  getParentRoute: () => rootRouteImport,
} as any)
const Harness03Route = Harness03RouteImport.update({
  id: '/harness-03',
  path: '/harness-03',
  getParentRoute: () => rootRouteImport,
} as any)
const Harness02Route = Harness02RouteImport.update({
  id: '/harness-02',
  path: '/harness-02',
  getParentRoute: () => rootRouteImport,
} as any)
const Harness01Route = Harness01RouteImport.update({
  id: '/harness-01',
  path: '/harness-01',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harness-01': typeof Harness01Route
  '/harness-02': typeof Harness02Route
  '/harness-03': typeof Harness03Route
  '/harness-04': typeof Harness04Route
  '/harness-05': typeof Harness05Route
  '/ia-bien-usada': typeof IaBienUsadaRoute
  '/mod-06': typeof Mod06Route
  '/mod-08': typeof Mod08Route
  '/mod-09': typeof Mod09Route
  '/von-neumann': typeof VonNeumannRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harness-01': typeof Harness01Route
  '/harness-02': typeof Harness02Route
  '/harness-03': typeof Harness03Route
  '/harness-04': typeof Harness04Route
  '/harness-05': typeof Harness05Route
  '/ia-bien-usada': typeof IaBienUsadaRoute
  '/mod-06': typeof Mod06Route
  '/mod-08': typeof Mod08Route
  '/mod-09': typeof Mod09Route
  '/von-neumann': typeof VonNeumannRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/harness-01': typeof Harness01Route
  '/harness-02': typeof Harness02Route
  '/harness-03': typeof Harness03Route
  '/harness-04': typeof Harness04Route
  '/harness-05': typeof Harness05Route
  '/ia-bien-usada': typeof IaBienUsadaRoute
  '/mod-06': typeof Mod06Route
  '/mod-08': typeof Mod08Route
  '/mod-09': typeof Mod09Route
  '/von-neumann': typeof VonNeumannRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/harness-01'
    | '/harness-02'
    | '/harness-03'
    | '/harness-04'
    | '/harness-05'
    | '/ia-bien-usada'
    | '/mod-06'
    | '/mod-08'
    | '/mod-09'
    | '/von-neumann'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/harness-01'
    | '/harness-02'
    | '/harness-03'
    | '/harness-04'
    | '/harness-05'
    | '/ia-bien-usada'
    | '/mod-06'
    | '/mod-08'
    | '/mod-09'
    | '/von-neumann'
  id:
    | '__root__'
    | '/'
    | '/harness-01'
    | '/harness-02'
    | '/harness-03'
    | '/harness-04'
    | '/harness-05'
    | '/ia-bien-usada'
    | '/mod-06'
    | '/mod-08'
    | '/mod-09'
    | '/von-neumann'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Harness01Route: typeof Harness01Route
  Harness02Route: typeof Harness02Route
  Harness03Route: typeof Harness03Route
  Harness04Route: typeof Harness04Route
  Harness05Route: typeof Harness05Route
  IaBienUsadaRoute: typeof IaBienUsadaRoute
  Mod06Route: typeof Mod06Route
  Mod08Route: typeof Mod08Route
  Mod09Route: typeof Mod09Route
  VonNeumannRoute: typeof VonNeumannRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/von-neumann': {
      id: '/von-neumann'
      path: '/von-neumann'
      fullPath: '/von-neumann'
      preLoaderRoute: typeof VonNeumannRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-09': {
      id: '/mod-09'
      path: '/mod-09'
      fullPath: '/mod-09'
      preLoaderRoute: typeof Mod09RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-08': {
      id: '/mod-08'
      path: '/mod-08'
      fullPath: '/mod-08'
      preLoaderRoute: typeof Mod08RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-06': {
      id: '/mod-06'
      path: '/mod-06'
      fullPath: '/mod-06'
      preLoaderRoute: typeof Mod06RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-bien-usada': {
      id: '/ia-bien-usada'
      path: '/ia-bien-usada'
      fullPath: '/ia-bien-usada'
      preLoaderRoute: typeof IaBienUsadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-05': {
      id: '/harness-05'
      path: '/harness-05'
      fullPath: '/harness-05'
      preLoaderRoute: typeof Harness05RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-04': {
      id: '/harness-04'
      path: '/harness-04'
      fullPath: '/harness-04'
      preLoaderRoute: typeof Harness04RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-03': {
      id: '/harness-03'
      path: '/harness-03'
      fullPath: '/harness-03'
      preLoaderRoute: typeof Harness03RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-02': {
      id: '/harness-02'
      path: '/harness-02'
      fullPath: '/harness-02'
      preLoaderRoute: typeof Harness02RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-01': {
      id: '/harness-01'
      path: '/harness-01'
      fullPath: '/harness-01'
      preLoaderRoute: typeof Harness01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Harness01Route: Harness01Route,
  Harness02Route: Harness02Route,
  Harness03Route: Harness03Route,
  Harness04Route: Harness04Route,
  Harness05Route: Harness05Route,
  IaBienUsadaRoute: IaBienUsadaRoute,
  Mod06Route: Mod06Route,
  Mod08Route: Mod08Route,
  Mod09Route: Mod09Route,
  VonNeumannRoute: VonNeumannRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
