/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VonNeumannRouteImport } from './routes/von-neumann'
import { Route as Sesion05RouteImport } from './routes/sesion-05'
import { Route as Sesion03RouteImport } from './routes/sesion-03'
import { Route as Sesion02RouteImport } from './routes/sesion-02'
import { Route as IaBienUsadaRouteImport } from './routes/ia-bien-usada'
import { Route as Harness05RouteImport } from './routes/harness-05'
import { Route as Harness04RouteImport } from './routes/harness-04'
import { Route as IndexRouteImport } from './routes/index'

const VonNeumannRoute = VonNeumannRouteImport.update({
  id: '/von-neumann',
  path: '/von-neumann',
  getParentRoute: () => rootRouteImport,
} as any)
const Sesion05Route = Sesion05RouteImport.update({
  id: '/sesion-05',
  path: '/sesion-05',
  getParentRoute: () => rootRouteImport,
} as any)
const Sesion03Route = Sesion03RouteImport.update({
  id: '/sesion-03',
  path: '/sesion-03',
  getParentRoute: () => rootRouteImport,
} as any)
const Sesion02Route = Sesion02RouteImport.update({
  id: '/sesion-02',
  path: '/sesion-02',
  getParentRoute: () => rootRouteImport,
} as any)
const IaBienUsadaRoute = IaBienUsadaRouteImport.update({
  id: '/ia-bien-usada',
  path: '/ia-bien-usada',
  getParentRoute: () => rootRouteImport,
} as any)
const Harness05Route = Harness05RouteImport.update({
  id: '/harness-05',
  path: '/harness-05',
  getParentRoute: () => rootRouteImport,
} as any)
const Harness04Route = Harness04RouteImport.update({
  id: '/harness-04',
  path: '/harness-04',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harness-04': typeof Harness04Route
  '/harness-05': typeof Harness05Route
  '/ia-bien-usada': typeof IaBienUsadaRoute
  '/sesion-02': typeof Sesion02Route
  '/sesion-03': typeof Sesion03Route
  '/sesion-05': typeof Sesion05Route
  '/von-neumann': typeof VonNeumannRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harness-04': typeof Harness04Route
  '/harness-05': typeof Harness05Route
  '/ia-bien-usada': typeof IaBienUsadaRoute
  '/sesion-02': typeof Sesion02Route
  '/sesion-03': typeof Sesion03Route
  '/sesion-05': typeof Sesion05Route
  '/von-neumann': typeof VonNeumannRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/harness-04': typeof Harness04Route
  '/harness-05': typeof Harness05Route
  '/ia-bien-usada': typeof IaBienUsadaRoute
  '/sesion-02': typeof Sesion02Route
  '/sesion-03': typeof Sesion03Route
  '/sesion-05': typeof Sesion05Route
  '/von-neumann': typeof VonNeumannRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/harness-04'
    | '/harness-05'
    | '/ia-bien-usada'
    | '/sesion-02'
    | '/sesion-03'
    | '/sesion-05'
    | '/von-neumann'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/harness-04'
    | '/harness-05'
    | '/ia-bien-usada'
    | '/sesion-02'
    | '/sesion-03'
    | '/sesion-05'
    | '/von-neumann'
  id:
    | '__root__'
    | '/'
    | '/harness-04'
    | '/harness-05'
    | '/ia-bien-usada'
    | '/sesion-02'
    | '/sesion-03'
    | '/sesion-05'
    | '/von-neumann'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Harness04Route: typeof Harness04Route
  Harness05Route: typeof Harness05Route
  IaBienUsadaRoute: typeof IaBienUsadaRoute
  Sesion02Route: typeof Sesion02Route
  Sesion03Route: typeof Sesion03Route
  Sesion05Route: typeof Sesion05Route
  VonNeumannRoute: typeof VonNeumannRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/von-neumann': {
      id: '/von-neumann'
      path: '/von-neumann'
      fullPath: '/von-neumann'
      preLoaderRoute: typeof VonNeumannRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesion-05': {
      id: '/sesion-05'
      path: '/sesion-05'
      fullPath: '/sesion-05'
      preLoaderRoute: typeof Sesion05RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesion-03': {
      id: '/sesion-03'
      path: '/sesion-03'
      fullPath: '/sesion-03'
      preLoaderRoute: typeof Sesion03RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesion-02': {
      id: '/sesion-02'
      path: '/sesion-02'
      fullPath: '/sesion-02'
      preLoaderRoute: typeof Sesion02RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-bien-usada': {
      id: '/ia-bien-usada'
      path: '/ia-bien-usada'
      fullPath: '/ia-bien-usada'
      preLoaderRoute: typeof IaBienUsadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-05': {
      id: '/harness-05'
      path: '/harness-05'
      fullPath: '/harness-05'
      preLoaderRoute: typeof Harness05RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harness-04': {
      id: '/harness-04'
      path: '/harness-04'
      fullPath: '/harness-04'
      preLoaderRoute: typeof Harness04RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Harness04Route: Harness04Route,
  Harness05Route: Harness05Route,
  IaBienUsadaRoute: IaBienUsadaRoute,
  Sesion02Route: Sesion02Route,
  Sesion03Route: Sesion03Route,
  Sesion05Route: Sesion05Route,
  VonNeumannRoute: VonNeumannRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
